### ISSUE TITLE
Find motifs when having the positions:

### ISSUE THREAD

**Issue by coraliegrobel** [EPFL-SV-cpp-projects/Team_18#14]

**Comment by FlaubertEPFL** [comment]
write the function "find_motif_with_Position()":
Takes the multimap <string(name chromosome), pair<int, int> (start position and stopposition) as an argument and returns a vector<vector<int>>, which is basically a vector containing all motifs. The strings are converted to a vector<int>.
The fonction "return_positions(string)":
You give as an argument the name of the chromosome of which you want to know all the start and stop positions.
The function returns a sorted (first element from small to big) vector<pair<int, int>> where the first int is the start position and the second int the stop position.
