### ISSUE TITLE
Squelette

### ISSUE THREAD

**Issue by loickreienbuhl** [EPFL-SV-cpp-projects/Team_18#5]

**Comment by npont** [comment]
pourquoi pas mettre l'action du void set_Sample (de la classe Sample) dans le constructeur de cette classe plutôt?

**Comment by mlpdh** [comment]
L’idée c’était de pouvoir mettre à jour le sample en attribut de configuration qd on prélève le fragment suivant dans le fichier FASTA... ou il faudrait en construire un nouveau chaque fois...
